package report

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/jung-kurt/gofpdf"
	"github.com/deptic-io/api/internal/compliance"
	"github.com/deptic-io/api/internal/scanner"
)

// ScanInfo holds high-level metadata about a scan.
type ScanInfo struct {
	ID          string
	RepoName    string
	RepoURL     string
	Ecosystem   string
	GeneratedAt string
}

// VulnSummary holds counts of vulnerabilities by severity.
type VulnSummary struct {
	Critical int
	High     int
	Medium   int
	Low      int
}

// VulnDetail holds information for a single vulnerability row.
type VulnDetail struct {
	PackageName    string
	PackageVersion string
	CVEID          string
	Severity       string
	Summary        string
}

// --- colour helpers ---------------------------------------------------------─

func setFillRGB(pdf *gofpdf.Fpdf, r, g, b int) {
	pdf.SetFillColor(r, g, b)
}

func setTextRGB(pdf *gofpdf.Fpdf, r, g, b int) {
	pdf.SetTextColor(r, g, b)
}

func setDrawRGB(pdf *gofpdf.Fpdf, r, g, b int) {
	pdf.SetDrawColor(r, g, b)
}

// colourDark  - near-black charcoal
const (
	darkR, darkG, darkB     = 25, 28, 36
	midR, midG, midB        = 55, 60, 75
	lightR, lightG, lightB  = 240, 242, 248
	accentR, accentG, accentB = 72, 128, 255
	greenR, greenG, greenB  = 50, 180, 100
	redR, redG, redB        = 220, 50, 50
	orangeR, orangeG, orangeB = 230, 120, 50
	white                   = 255
)

// pageW / pageH for A4 portrait (mm)
const pageW = 210.0
const pageH = 297.0
const margin = 18.0
const contentW = pageW - margin*2

// --- page skeleton -----------------------------------------------------------


func safeText(s string) string {
	return strings.Map(func(r rune) rune {
		if r > 127 { return '-' }
		return r
	}, s)
}

func newPDF() *gofpdf.Fpdf {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(margin, margin, margin)
	pdf.SetAutoPageBreak(true, margin+14)
	pdf.SetFooterFunc(func() {
		pdf.SetY(-14)
		setTextRGB(pdf, 130, 135, 150)
		pdf.SetFont("Helvetica", "", 8)
		pdf.CellFormat(contentW, 6, safeText("Generated by DEPTIC.io - Automated DEPTIC Compliance Platform"), "T", 0, "C", false, 0, "")
	})
	return pdf
}

// sectionHeader draws a bold dark-bg section title bar.
func sectionHeader(pdf *gofpdf.Fpdf, title string) {
	setFillRGB(pdf, darkR, darkG, darkB)
	setTextRGB(pdf, white, white, white)
	pdf.SetFont("Helvetica", "B", 13)
	pdf.CellFormat(contentW, 9, safeText(title), "", 1, "L", true, 0, "")
	pdf.Ln(3)
}

func subHeader(pdf *gofpdf.Fpdf, sub string) {
	setTextRGB(pdf, midR, midG, midB)
	pdf.SetFont("Helvetica", "I", 9)
	pdf.CellFormat(contentW, 6, safeText(sub), "", 1, "L", false, 0, "")
	pdf.Ln(2)
}

func hRule(pdf *gofpdf.Fpdf) {
	setDrawRGB(pdf, accentR, accentG, accentB)
	pdf.SetLineWidth(0.4)
	y := pdf.GetY()
	pdf.Line(margin, y, pageW-margin, y)
	pdf.Ln(4)
}



// --- Page 1 - Cover ---------------------------------------------------------─

func buildCoverPage(pdf *gofpdf.Fpdf, scan ScanInfo, compCount int, vs VulnSummary, ntia compliance.NTIAResult) {
	pdf.AddPage()

	// --- gradient-like header block ---
	setFillRGB(pdf, darkR, darkG, darkB)
	pdf.Rect(0, 0, pageW, 65, "F")

	// Logo text
	setTextRGB(pdf, accentR, accentG, accentB)
	pdf.SetFont("Helvetica", "B", 28)
	pdf.SetXY(margin, 12)
	pdf.CellFormat(contentW, 14, safeText("DEPTIC.io"), "", 1, "L", false, 0, "")

	// Main title
	setTextRGB(pdf, white, white, white)
	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetX(margin)
	pdf.CellFormat(contentW, 9, safeText("Software Bill of Materials"), "", 1, "L", false, 0, "")
	pdf.SetX(margin)
	pdf.CellFormat(contentW, 9, safeText("Compliance Report"), "", 1, "L", false, 0, "")

	// Repo name subtitle
	setTextRGB(pdf, 170, 185, 220)
	pdf.SetFont("Helvetica", "", 11)
	pdf.SetX(margin)
	pdf.CellFormat(contentW, 7, safeText(scan.RepoName), "", 1, "L", false, 0, "")

	// Generated at
	setTextRGB(pdf, 120, 135, 160)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetX(margin)
	pdf.CellFormat(contentW, 6, safeText("Generated: "+scan.GeneratedAt), "", 1, "L", false, 0, "")

	// Body area starts at y=75
	pdf.SetY(78)

	hRule(pdf)

	// -- Summary boxes --------------------------------------------------------
	boxW := contentW / 3
	boxH := 28.0
	y := pdf.GetY()

	drawSummaryBox(pdf, margin, y, boxW-3, boxH,
		"Total Components", fmt.Sprintf("%d", compCount),
		accentR, accentG, accentB)
	drawSummaryBox(pdf, margin+boxW, y, boxW-3, boxH,
		"Critical CVEs", fmt.Sprintf("%d", vs.Critical),
		redR, redG, redB)

	// NTIA score box - green if compliant, red if not
	var scoreR, scoreG, scoreB int
	if ntia.Compliant {
		scoreR, scoreG, scoreB = greenR, greenG, greenB
	} else {
		scoreR, scoreG, scoreB = redR, redG, redB
	}
	drawSummaryBox(pdf, margin+boxW*2, y, boxW-3, boxH,
		"NTIA Score", fmt.Sprintf("%d/100", ntia.Score),
		scoreR, scoreG, scoreB)

	pdf.SetY(y + boxH + 6)

	// -- Scan details ---------------------------------------------------------
	pdf.Ln(4)
	hRule(pdf)

	labelVal := func(label, val string) {
		setTextRGB(pdf, midR, midG, midB)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.CellFormat(38, 6, safeText(label+":"), "", 0, "L", false, 0, "")
		setTextRGB(pdf, darkR, darkG, darkB)
		pdf.SetFont("Helvetica", "", 9)
		pdf.CellFormat(contentW-38, 6, safeText(val), "", 1, "L", false, 0, "")
	}

	labelVal("Scan ID", scan.ID)
	labelVal("Repository", scan.RepoURL)
	labelVal("Ecosystem", scan.Ecosystem)

	pdf.Ln(6)
	hRule(pdf)

	// -- Vulnerability breakdown mini-table -----------------------------------
	setTextRGB(pdf, darkR, darkG, darkB)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(contentW, 7, safeText("Vulnerability Breakdown"), "", 1, "L", false, 0, "")
	pdf.Ln(1)

	drawVulnPill(pdf, "CRITICAL", vs.Critical, redR, redG, redB)
	drawVulnPill(pdf, "HIGH", vs.High, orangeR, orangeG, orangeB)
	drawVulnPill(pdf, "MEDIUM", vs.Medium, 200, 160, 40)
	drawVulnPill(pdf, "LOW", vs.Low, 80, 160, 200)

	// footer
}

func drawSummaryBox(pdf *gofpdf.Fpdf, x, y, w, h float64, label, value string, cr, cg, cb int) {
	// Light card background
	setFillRGB(pdf, lightR, lightG, lightB)
	setDrawRGB(pdf, cr, cg, cb)
	pdf.SetLineWidth(0.5)
	pdf.RoundedRect(x, y, w, h, 2, "1234", "FD")

	// Colour bar on left
	setFillRGB(pdf, cr, cg, cb)
	pdf.Rect(x, y, 3.5, h, "F")

	// Label
	setTextRGB(pdf, midR, midG, midB)
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetXY(x+5, y+3)
	pdf.CellFormat(w-7, 5, safeText(label), "", 1, "L", false, 0, "")

	// Value
	setTextRGB(pdf, cr, cg, cb)
	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetXY(x+5, y+9)
	pdf.CellFormat(w-7, 10, safeText(value), "", 1, "L", false, 0, "")
}

func drawVulnPill(pdf *gofpdf.Fpdf, label string, count int, cr, cg, cb int) {
	pillW := 44.0
	pillH := 10.0
	x := pdf.GetX()
	y := pdf.GetY()

	setFillRGB(pdf, cr, cg, cb)
	pdf.RoundedRect(x, y, pillW, pillH, 1.5, "1234", "F")

	setTextRGB(pdf, white, white, white)
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetXY(x, y+1)
	pdf.CellFormat(pillW, 4, safeText(label), "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "B", 11)
	pdf.SetXY(x, y+5)
	pdf.CellFormat(pillW, 5, safeText(fmt.Sprintf("%d", count)), "", 0, "C", false, 0, "")

	pdf.SetXY(x+pillW+3, y)
}

// --- Page 2 - NTIA Compliance ------------------------------------------------

func buildNTIAPage(pdf *gofpdf.Fpdf, ntia compliance.NTIAResult, euCompliant bool) {
	pdf.AddPage()

	sectionHeader(pdf, "NTIA Minimum Elements Assessment")
	subHeader(pdf, "US Executive Order 14028 Compliance")

	// Compliance status banner
	var bannerR, bannerG, bannerB int
	bannerLabel := "NON-COMPLIANT"
	if ntia.Compliant {
		bannerR, bannerG, bannerB = greenR, greenG, greenB
		bannerLabel = "COMPLIANT"
	} else {
		bannerR, bannerG, bannerB = redR, redG, redB
	}

	setFillRGB(pdf, bannerR, bannerG, bannerB)
	setTextRGB(pdf, white, white, white)
	pdf.SetFont("Helvetica", "B", 12)
	y := pdf.GetY()
	pdf.RoundedRect(margin, y, contentW/2-3, 10, 2, "1234", "FD")
	pdf.SetXY(margin, y+2)
	pdf.CellFormat(contentW/2-3, 6, safeText("NTIA: "+bannerLabel), "", 0, "C", false, 0, "")

	// EU CRA status
	euLabel := "NON-COMPLIANT"
	var euR, euG, euB int
	if euCompliant {
		euR, euG, euB = greenR, greenG, greenB
		euLabel = "COMPLIANT"
	} else {
		euR, euG, euB = redR, redG, redB
	}
	setFillRGB(pdf, euR, euG, euB)
	pdf.RoundedRect(margin+contentW/2+3, y, contentW/2-3, 10, 2, "1234", "FD")
	pdf.SetXY(margin+contentW/2+3, y+2)
	pdf.CellFormat(contentW/2-3, 6, safeText("EU CRA: "+euLabel), "", 1, "C", false, 0, "")

	pdf.Ln(5)

	// Score bar
	setTextRGB(pdf, midR, midG, midB)
	pdf.SetFont("Helvetica", "", 9)
	pdf.CellFormat(contentW, 5, safeText(fmt.Sprintf("Compliance Score: %d / 100", ntia.Score)), "", 1, "L", false, 0, "")
	pdf.Ln(1)

	// -- Elements table --------------------------------------------------------
	colWidths := [4]float64{60, 22, 22, contentW - 60 - 22 - 22}

	// Table header
	setFillRGB(pdf, darkR, darkG, darkB)
	setTextRGB(pdf, white, white, white)
	pdf.SetFont("Helvetica", "B", 8)
	headers := []string{"Element Name", "Status", "Coverage %", "Detail"}
	for i, h := range headers {
		pdf.CellFormat(colWidths[i], 7, safeText(h), "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)

	// Rows
	for idx, el := range ntia.Elements {
		detailText := safeText(el.Detail)
		pdf.SetFont("Helvetica", "", 8)
		lines := pdf.SplitLines([]byte(detailText), colWidths[3]-2)
		numLines := len(lines)
		if numLines == 0 {
			numLines = 1
		}
		
		lineH := 4.0
		rowH := lineH * float64(numLines)
		if rowH < 7.0 {
			rowH = 7.0
			lineH = 7.0 / float64(numLines)
		}

		x := pdf.GetX()
		y := pdf.GetY()
		if y + rowH > pageH - margin - 14 {
			pdf.AddPage()
			y = pdf.GetY()
		}

		// Alternate row shading
		if idx%2 == 0 {
			setFillRGB(pdf, 245, 246, 252)
		} else {
			setFillRGB(pdf, white, white, white)
		}

		var statusR, statusG, statusB int
		statusText := "PASS"
		if el.Passed {
			statusR, statusG, statusB = greenR, greenG, greenB
		} else {
			statusR, statusG, statusB = redR, redG, redB
			statusText = "FAIL"
		}

		setTextRGB(pdf, darkR, darkG, darkB)
		pdf.SetFont("Helvetica", "", 8)
		pdf.CellFormat(colWidths[0], rowH, safeText(el.Name), "1", 0, "L", true, 0, "")

		// Status cell with colour
		setFillRGB(pdf, statusR, statusG, statusB)
		setTextRGB(pdf, white, white, white)
		pdf.SetFont("Helvetica", "B", 8)
		pdf.CellFormat(colWidths[1], rowH, safeText(statusText), "1", 0, "C", true, 0, "")

		// Coverage
		if idx%2 == 0 {
			setFillRGB(pdf, 245, 246, 252)
		} else {
			setFillRGB(pdf, white, white, white)
		}
		setTextRGB(pdf, darkR, darkG, darkB)
		pdf.SetFont("Helvetica", "", 8)
		pdf.CellFormat(colWidths[2], rowH, safeText(fmt.Sprintf("%d%%", el.Coverage)), "1", 0, "C", true, 0, "")

		// Detail - multi-line
		xLast := x + colWidths[0] + colWidths[1] + colWidths[2]
		pdf.Rect(xLast, y, colWidths[3], rowH, "DF")
		pdf.SetXY(xLast + 1, y + (rowH-(float64(numLines)*lineH))/2)
		pdf.MultiCell(colWidths[3]-2, lineH, detailText, "0", "L", false)
		pdf.SetXY(margin, y + rowH)
	}

	// -- Recommendations ------------------------------------------------------─
	if len(ntia.Recommendations) > 0 {
		pdf.Ln(5)
		setFillRGB(pdf, darkR, darkG, darkB)
		setTextRGB(pdf, white, white, white)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(contentW, 7, safeText("Recommendations"), "", 1, "L", true, 0, "")
		pdf.Ln(2)

		for i, rec := range ntia.Recommendations {
			setTextRGB(pdf, darkR, darkG, darkB)
			pdf.SetFont("Helvetica", "", 8)
			pdf.MultiCell(contentW, 5, safeText(fmt.Sprintf("%d. %s", i+1, rec)), "", "L", false)
			pdf.Ln(1)
		}
	}
}

// --- Page 3 - Vulnerability Summary -----------------------------------------

func buildVulnPage(pdf *gofpdf.Fpdf, vs VulnSummary, vulns []VulnDetail) {
	pdf.AddPage()

	sectionHeader(pdf, "Security Vulnerability Report")
	subHeader(pdf, fmt.Sprintf("Top %d most severe findings", min(len(vulns), 20)))

	pdf.Ln(2)

	// 4 severity boxes
	boxW := contentW / 4
	boxH := 24.0
	y := pdf.GetY()

	type sevBox struct {
		label string
		count int
		r, g, b int
	}
	boxes := []sevBox{
		{"Critical", vs.Critical, redR, redG, redB},
		{"High", vs.High, orangeR, orangeG, orangeB},
		{"Medium", vs.Medium, 200, 160, 40},
		{"Low", vs.Low, 80, 160, 200},
	}
	for i, b := range boxes {
		drawSummaryBox(pdf, margin+float64(i)*boxW, y, boxW-2, boxH, b.label, fmt.Sprintf("%d", b.count), b.r, b.g, b.b)
	}
	pdf.SetY(y + boxH + 6)

	pdf.Ln(2)

	// -- Vulnerability table ---------------------------------------------------
	colWidths := [5]float64{40, 22, 40, 22, contentW - 40 - 22 - 40 - 22}

	// Table header
	setFillRGB(pdf, darkR, darkG, darkB)
	setTextRGB(pdf, white, white, white)
	pdf.SetFont("Helvetica", "B", 8)
	headers := []string{"Package", "Version", "CVE ID", "Severity", "Summary"}
	for i, h := range headers {
		pdf.CellFormat(colWidths[i], 7, safeText(h), "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)

	limit := 20
	if len(vulns) < limit {
		limit = len(vulns)
	}

	for idx := 0; idx < limit; idx++ {
		v := vulns[idx]

		var fillR, fillG, fillB int
		switch strings.ToUpper(v.Severity) {
		case "CRITICAL":
			fillR, fillG, fillB = 255, 230, 230
		case "HIGH":
			fillR, fillG, fillB = 255, 240, 220
		default:
			if idx%2 == 0 {
				fillR, fillG, fillB = 245, 246, 252
			} else {
				fillR, fillG, fillB = white, white, white
			}
		}
		summaryText := safeText(v.Summary)
		pdf.SetFont("Helvetica", "", 7)
		lines := pdf.SplitLines([]byte(summaryText), colWidths[4]-2)
		numLines := len(lines)
		if numLines == 0 { numLines = 1 }
		lineH := 3.5
		rowH := lineH * float64(numLines)
		if rowH < 7.0 {
			rowH = 7.0
			lineH = 7.0 / float64(numLines)
		}

		x := pdf.GetX()
		y := pdf.GetY()
		if y + rowH > pageH - margin - 14 {
			pdf.AddPage()
			y = pdf.GetY()
		}

		setFillRGB(pdf, fillR, fillG, fillB)
		setTextRGB(pdf, darkR, darkG, darkB)
		pdf.SetFont("Helvetica", "", 7)

		pdf.CellFormat(colWidths[0], rowH, safeText(truncate(v.PackageName, 22)), "1", 0, "L", true, 0, "")
		pdf.CellFormat(colWidths[1], rowH, safeText(truncate(v.PackageVersion, 14)), "1", 0, "C", true, 0, "")
		pdf.CellFormat(colWidths[2], rowH, safeText(truncate(v.CVEID, 24)), "1", 0, "L", true, 0, "")

		// Severity badge
		var sevR, sevG, sevB int
		switch strings.ToUpper(v.Severity) {
		case "CRITICAL":
			sevR, sevG, sevB = redR, redG, redB
		case "HIGH":
			sevR, sevG, sevB = orangeR, orangeG, orangeB
		case "MEDIUM":
			sevR, sevG, sevB = 200, 160, 40
		default:
			sevR, sevG, sevB = 80, 160, 200
		}
		setFillRGB(pdf, sevR, sevG, sevB)
		setTextRGB(pdf, white, white, white)
		pdf.SetFont("Helvetica", "B", 7)
		pdf.CellFormat(colWidths[3], rowH, safeText(strings.ToUpper(v.Severity)), "1", 0, "C", true, 0, "")

		setFillRGB(pdf, fillR, fillG, fillB)
		setTextRGB(pdf, darkR, darkG, darkB)
		pdf.SetFont("Helvetica", "", 7)
		xLast := x + colWidths[0] + colWidths[1] + colWidths[2] + colWidths[3]
		pdf.Rect(xLast, y, colWidths[4], rowH, "DF")
		pdf.SetXY(xLast + 1, y + (rowH-(float64(numLines)*lineH))/2)
		pdf.MultiCell(colWidths[4]-2, lineH, summaryText, "0", "L", false)
		pdf.SetXY(margin, y + rowH)
	}
}

// --- Page 4 - Component Inventory --------------------------------------------

func buildComponentPage(pdf *gofpdf.Fpdf, components []scanner.Package, totalComponents int) {
	pdf.AddPage()

	displayCount := totalComponents
	if displayCount > 100 {
		displayCount = 100
	}

	sectionHeader(pdf, fmt.Sprintf("Component Inventory (showing %d of %d)", displayCount, totalComponents))
	subHeader(pdf, "Resolved packages across all dependency levels")

	pdf.Ln(2)

	colWidths := [6]float64{10, 50, 25, 35, 22, 12}

	// Table header
	setFillRGB(pdf, darkR, darkG, darkB)
	setTextRGB(pdf, white, white, white)
	pdf.SetFont("Helvetica", "B", 7)
	headers := []string{"#", "Package Name", "Version", "License", "Ecosystem", "Depth"}
	for i, h := range headers {
		pdf.CellFormat(colWidths[i], 6, safeText(h), "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)

	for idx := 0; idx < displayCount && idx < len(components); idx++ {
		pkg := components[idx]
		if idx%2 == 0 {
			setFillRGB(pdf, 245, 246, 252)
		} else {
			setFillRGB(pdf, white, white, white)
		}
		setTextRGB(pdf, darkR, darkG, darkB)
		pdf.SetFont("Helvetica", "", 7)

		rowH := 5.5
		pdf.CellFormat(colWidths[0], rowH, safeText(fmt.Sprintf("%d", idx+1)), "1", 0, "C", true, 0, "")
		pdf.CellFormat(colWidths[1], rowH, safeText(truncate(pkg.Name, 35)), "1", 0, "L", true, 0, "")
		pdf.CellFormat(colWidths[2], rowH, safeText(truncate(pkg.Version, 16)), "1", 0, "C", true, 0, "")
		pdf.CellFormat(colWidths[3], rowH, safeText(truncate(pkg.License, 22)), "1", 0, "L", true, 0, "")
		pdf.CellFormat(colWidths[4], rowH, safeText(truncate(pkg.Ecosystem, 14)), "1", 0, "C", true, 0, "")
		pdf.CellFormat(colWidths[5], rowH, safeText(fmt.Sprintf("%d", pkg.Depth)), "1", 1, "C", true, 0, "")
	}

	// Note at bottom
	pdf.Ln(4)
	setTextRGB(pdf, 100, 110, 130)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.MultiCell(contentW, 5, safeText("Full inventory available in CycloneDX/SPDX export. Use the DEPTIC.io dashboard to download complete machine-readable DEPTICs."), "", "L", false)
}

// --- Public entry-point ------------------------------------------------------

// GeneratePDFReport generates a 4-page A4 PDF compliance report and returns
// the raw bytes. vulns may be nil/empty; in that case the vulnerability page
// will still render with zero counts.
func GeneratePDFReport(
	scan ScanInfo,
	components []scanner.Package,
	vulnSummary VulnSummary,
	vulnDetails []VulnDetail,
	ntia compliance.NTIAResult,
	euCompliant bool,
) ([]byte, error) {
	pdf := newPDF()

	buildCoverPage(pdf, scan, len(components), vulnSummary, ntia)
	buildNTIAPage(pdf, ntia, euCompliant)
	buildVulnPage(pdf, vulnSummary, vulnDetails)
	buildComponentPage(pdf, components, len(components))

	if pdf.Error() != nil {
		return nil, pdf.Error()
	}

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// --- helpers -----------------------------------------------------------------

func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max-1] + "..."
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
